### ISSUE TITLE
Package Manager cannot find com.pixelsforglory.extensions@1.0.10

### ISSUE THREAD

**Issue by renb0** [PixelsForGlory/VoronoiDiagram#3]
`[Package Manager Window] Cannot perform upm operation: Unable to add package [https://github.com/PixelsForGlory/VoronoiDiagram.git]:
  Package com.pixelsforglory.voronoidiagram@https://github.com/PixelsForGlory/VoronoiDiagram.git has invalid dependencies or related test packages:
    com.pixelsforglory.extensions (dependency): Package [com.pixelsforglory.extensions@1.0.10] cannot be found [NotFound].
UnityEditor.EditorApplication:Internal_CallUpdateFunctions () (at /Users/bokken/buildslave/unity/build/Editor/Mono/EditorApplication.cs:356)`

**Comment by afuzzyllama** [comment]
I added a prerequisite to the install which should solve that issue.  Thanks for submitting a ticket!
